# Generated by Django 5.2.7 on 2025-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='Maharashtra', max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('financial_year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=20)),
                ('total_households_applied', models.IntegerField(default=0)),
                ('total_households_allotted', models.IntegerField(default=0)),
                ('total_persondays_generated', models.BigIntegerField(default=0)),
                ('total_expenditure', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('district_name', 'financial_year', 'month')},
            },
        ),
    ]
